language: generic

jobs:
  include:
  - stage: Continuous Integration
    name: SwiftLint
    os: osx
    osx_image: xcode11
    script:
    - make lint
  - stage: Continuous Integration
    name: SwiftPM macOS
    os: osx
    osx_image: xcode11.2
    script:
    - swift test --parallel
  - stage: Continuous Integration
    name: SwiftPM Linux
    os: Linux
    dist: trusty
    sudo: required
    install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
    - swiftenv install 5.1
    - swiftenv local 5.1
    - swift --version
    script:
    - swift test --parallel
  - stage: Continuous Integration
    name: Installation from Source (macOS)
    os: osx
    osx_image: xcode11.2
    script:
    - git clone --depth 1 https://github.com/minuscorp/ModuleInterface.git
    - cd ModuleInterface
    - make install
    - moduleinterface version